<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6956" started-at="2018-03-13T14:26:16Z" finished-at="2018-03-13T14:26:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6956" started-at="2018-03-13T14:26:16Z" finished-at="2018-03-13T14:26:23Z">
      <class name="testCases.Sanity">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testCases.Sanity@735b5592]" name="beforeClass" is-config="true" duration-ms="6" started-at="2018-03-13T16:26:16Z" finished-at="2018-03-13T16:26:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="createDriver(java.lang.String)[pri:0, instance:testCases.Sanity@735b5592]" name="createDriver" is-config="true" duration-ms="4565" started-at="2018-03-13T16:26:16Z" finished-at="2018-03-13T16:26:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDriver -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testCases.Sanity@735b5592]" name="beforeMethod" is-config="true" duration-ms="101" started-at="2018-03-13T16:26:21Z" finished-at="2018-03-13T16:26:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="assertOriginNotExistsInDay()[pri:0, instance:testCases.Sanity@735b5592]" name="assertOriginNotExistsInDay" duration-ms="1345" started-at="2018-03-13T16:26:21Z" finished-at="2018-03-13T16:26:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [לישוב כפר נטר אין שירות ביום מבוקש. בחר יום אחר.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [לישוב כפר נטר אין שירות ביום מבוקש. בחר יום אחר.] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at extensiones.Assertiones.assertValueExistsString(Assertiones.java:27)
	at testCases.Sanity.assertOriginNotExistsInDay(Sanity.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertOriginNotExistsInDay -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testCases.Sanity@735b5592]" name="afterMethod" is-config="true" duration-ms="926" started-at="2018-03-13T16:26:22Z" finished-at="2018-03-13T16:26:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testCases.Sanity -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
